# Generated by Django 4.1.3 on 2022-12-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="username",
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("username", "context")},
        ),
    ]
