# Generated by Django 4.1.3 on 2023-01-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_topic_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password_hash',
            field=models.CharField(max_length=128),
        ),
    ]
